name: Generate Doxygen Documentation

on:
  push:
    branches:
      - path-2
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@1.9.8
